services:
  my-postgres-service:
    image: postgres:15
    container_name: dev-postgres
    ports:
      - "5432:5432"
    environment:
      DB_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payments" ]
      interval: 5s
      timeout: 5s
      retries: 5


  payments-service:
    image: payments-service
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      my-postgres-service:
        condition: service_healthy


volumes:
  pg_data:
