spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/local
    username: admin
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_schema: local
  flyway:
    enabled: false
#    validate-on-migrate: true
#    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

flyway:
  enabled: true
  # locations: classpath:db/migration # If necessary.
  baseline-on-migrate: true
  baseline-version: 1