name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: dummyuser
          POSTGRES_PASSWORD: dummypassword
          POSTGRES_DB: dummyname
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables from Secrets
        run: |
          echo "DB_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Compile
        run: mvn clean compile

      - name: Run Tests
        run: mvn test

      - name: Package
        run: mvn package -DskipTests

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: |
          docker compose down -v || true
          docker compose up --build -d

      - name: Wait for Postgres
        run: |
          echo "Waiting for Postgres..."
          until docker exec dev-postgres pg_isready -U payments; 
          do sleep 2
          done

      - name: Wait for Spring Boot Service
        run: |
          echo "Waiting for Payments Service to start..."
          until curl -s http://localhost:8080/actuator/health | grep UP; 
          do sleep 2
          done

      - name: Run integration Tests
        run: mvn verify

      - name: Tear down containers
        run: docker compose down -v
        

#  docker-build-and-push:
#    needs: build-and-test
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build Docker image
#        run: |
#          docker build -t my-app:${{ github.sha }} .
#
#      - name: Push Docker image
#        run: |
#          docker tag my-app:${{ github.sha }} my-dockerhub-user/my-app:latest
#          docker push my-dockerhub-user/my-app:latest
